### PR TITLE
Workflow.md fixes

### PR DESCRIPTION
**Pull request by rodsan0**

### CODE REVIEW

**Comment by mmore500** [comment]
@rodsan0 could you add your higher-level feedback as comments on this PR?

**Comment by rodsan0** [comment]
- [ ] This page has many sections. It might be good to add a Table of Contents directive near the beginning. 
- [ ] Add warning block to line 14
- [ ] Simplify line 18 ("To see the help message, run the script with no arguments [...]")
- [ ] Maybe move the definition of data in line 80 to line 21.
- [ ] I don't think at any point we mention what type of data we are recording, but it might be worth doing it under or before the Experimental Evolution section too.
- [ ] On line 55 it might be neat to mention why this happens for interested readers.
- [ ] On line 97 it might be useful to add comments explaining each of the key groups (OSF, PushOver, AWS, Twitter) as not every user might need to define them.
- [ ] Mention some (possibly free) alternatives to S3 on line 120, like bitbucket. 
- [ ] On the same line, it might be useful to estimate what "current usage" is so that readers aren't concerned about cost. 
- [ ] We should move 148-149 to after line 139, as the clarification that caching will only work if the same container is used every time is relevant.
- [ ] Adding onto the prior point, it might be useful to also specify _how_ one can get the container hash.
- [ ] Simplify line 143 ("this" mentioned twice).
- [ ] Add warning block to line 151.
- [ ] Add `bash` tag to code blocks in lines 181, 192, 203, and 212.
- [ ] On or before line 240, what is "nopout"? Why do we want to do this? How do we determine what instructions to NOP-out?
- [ ] On line 266 (or in a prior, separate section), might be useful to explain how fitness is assessed. 
- [ ] On line 291, why do we want to collate data? How often should/can we do this?

**Comment by mmore500** [comment]
awesome feedback! I'm going to go thru edit the todo list in order to comment on each suggestion

**Comment by mmore500** [comment]
I didn't comment on everything, but all of these look like good ideas to fix. @rodsan0 could you take a crack at making edits to apply these suggestions and @ me for any suggestions you want more details on from my end or you think it would just be easier for me to apply?

**Pull request merged**
